### PR TITLE
Fix async subscription context

### LINKED ISSUE #208: Federation: Handle situation when graphql subscribe result is not AsyncIterable.
https://github.com/mcollina/fastify-gql/blob/master/lib/subscription-connection.js#L88 

Graphql's subscribe method doesn't return AsyncIterable always. It also may return simple ExecutionResult. And if it will return it, we'll get an error.

It's pretty much the same case as in https://github.com/mcollina/fastify-gql/pull/174, when ExecutionResult just ignored.

### LINKED ISSUE #235: Async subscription context kills the subscriptions.
I opened a draft PR (#234)  showing a bug that happens when the context for the subscriptions is an async function, I discovered it trying to make the context based on an database request, so I simulated the situation adding an artificial delay on a existing test and it did fail as expected.

In theory the code is awaiting (https://github.com/mcollina/fastify-gql/blob/master/lib/subscription.js#L27), but there seems to be a weird race condition somewhere.

### PR DESCRIPTION
**Pull request by PabloSzx**
This PR is just a draft for a failing test that shows the async subscription context bug.

It basically the same as the existing test for custom context, but with an artificial delay simulating a common http request delay.

EDIT: Added fix.

Fixes #235
Fixes #208

### CODE REVIEW

**Comment by mcollina** [comment]
Would you mind to also fix it? I'm not sure what's the problem:/

**Comment by PabloSzx** [comment]
> Would you mind to also fix it? I'm not sure what's the problem:/

image

image

I found this solution (that could be improved with an `isPromise` helper function), which is to basically let the socket connection be created and delay the await until `handleConnectionInit`.

I'd like to know if it sounds good to you.

File: lib/subscription.js [hunk 1]
```diff
@@ -24,7 +24,15 @@ function createConnectionHandler ({ schema, subscriber, fastify, onConnect, lruG
     let context = {}
     if (subscriptionContextFn) {
       try {
-        context = await subscriptionContextFn(connection, request)
+        context = subscriptionContextFn(connection, request)
+
+        if (context instanceof Promise) {
```
Comment (PabloSzx) [inline lib/subscription.js:29]: The async error was not being catched without doing this

File: lib/subscription-connection.js [hunk 2]
```diff
@@ -83,6 +83,17 @@ module.exports = class SubscriptionConnection {
   }
 
   async handleConnectionInit (data) {
+    if (this.context instanceof Promise) {
+      try {
+        this.context = await this.context
+      } catch (err) {
+        this.fastify.log.error(err)
```
Comment (PabloSzx) [inline lib/subscription-connection.js:90]: These couple of lines are not being tested, but I'm not sure if it's completely safe to just simply remove the try/catch, just because of the catch in `lib/subscription.js`

**Comment by PabloSzx** [comment]
> (or `instanceof Promise` if it should only support native Promises).

In the last changes I just assumed this, I honestly don't know if I can assume this

File: lib/subscription-connection.js (hunk 2 above)
Comment (PabloSzx) [reply lib/subscription-connection.js:90]: Nevermind, I just sent the message 'connection_init' in the intended test and it covered it. 100% coverage.

**Comment by PabloSzx** [comment]
I found another kinda important thing, when an error happens inside the execution of a subscription the error is not being catched properly, and it just replies with `the result is not async iterable` .

Following the [type definitions docs](https://github.com/graphql/graphql-js/blob/master/src/subscription/subscribe.d.ts#L22) in `graphql-js` `subscribe` function, those errors are returned in the execution results without the promise itself being thrown.

I just added
```js
if (result.errors) {
      throw result.errors[0];
}
``` 

[in subscription-connection.js](https://github.com/mcollina/fastify-gql/blob/master/lib/subscription-connection.js#L139)

And it works as expected.


I don't know if I should add it to this PR 🤷‍♂️

**Comment by asciidisco** [comment]
@PabloSzx I wonder if your latest finding might be related to https://github.com/mcollina/fastify-gql/issues/208

**Comment by PabloSzx** [comment]
> @PabloSzx I wonder if your latest finding might be related to #208

Yes, it is,  it's ok if you assigned yourself this fix yourself👍 

The `graphql` package itself validates the error thrown in the execution, it means there should be no need of validating the error inside result.errors, but I am not sure if it's needed to handle that there might be more than a single error.

<details><summary>Test I made in subscription.js if it's helpful at all</summary>
<p>

```js
test('subscription server send correct error if execution throws', t => {
  const app = Fastify()
  t.tearDown(() => app.close())

  const emitter = mq()
  const schema = `
    type Notification {
      id: ID!
      message: String
    }

    type Query {
      notifications: [Notification]
    }

    type Subscription {
      notificationAdded: Notification
    }
  `

  const resolvers = {
    Subscription: {
      notificationAdded: {
        subscribe: () => {
          throw Error('custom execution error')
        }
      }
    }
  }

  app.register(GQL, {
    schema,
    resolvers,
    subscription: {
      emitter
    }
  })

  app.listen(0, err => {
    t.error(err)

    const ws = new WebSocket('ws://localhost:' + (app.server.address()).port + '/graphql', 'graphql-ws')
    const client = WebSocket.createWebSocketStream(ws, { encoding: 'utf8', objectMode: true })
    t.tearDown(client.destroy.bind(client))
    client.setEncoding('utf8')

    client.write(JSON.stringify({
      type: 'connection_init'
    }))

    client.write(JSON.stringify({
      id: 1,
      type: 'start',
      payload: {
        query: `
          subscription {
            notificationAdded {
              id
              message
            }
          }
        `
      }
    }))

    client.on('data', chunk => {
      const data = JSON.parse(chunk)

      if (data.id === 1 && data.type === 'error') {
        t.equal(chunk, JSON.stringify({
          type: 'error',
          id: 1,
          payload: 'custom execution error'
        }))

        client.end()
        t.end()
      }
    })
  })
})
```

</p>
</details>

**Comment by PacoDu** [comment]
I confirm the issue if the contextFn is async the subscription listener is missing the messages sent in the 1st PR test, but the 2nd test works. I guess we can't do async stuff before binding the message handler.

I think it would be better to remove the context creation from `createConnectionHandler` and pass the `subscriptionContextFn` to `SubscriptionConnection` constructor. 
But this rises an other issue concerning `connection_init` and message order.

Based on apollo implementation https://github.com/apollographql/subscriptions-transport-ws/blob/52758bfba6190169a28078ecbafd2e457a2ff7a8/src/server.ts and https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md, if an `onConnect` handler is defined and returns `false` a `GQL_START` message should return a `GQL_CONNECTION_ERROR`.

**Comment by asciidisco** [comment]
@PabloSzx I just assigned myself as an ToDo item, because the person that has created the issue seems to be not interested in fixing & I have a slight feeling that this can hit us as well once we're done migrating from Apollo to Fastify. That being said, I would suggest that you can re-assign this to you & I also think it would be reasonable to fix it within this PR (of course, this is just my subjective opinion)

File: lib/subscription.js (hunk 1 above)
Comment (mcollina) [reply lib/subscription.js:29]: I don't understand why using `await` would not have worked. can you articulae?

**Comment by PabloSzx** [comment]
> I confirm the issue if the contextFn is async the subscription listener is missing the messages sent in the 1st PR test, but the 2nd test works. I guess we can't do async stuff before binding the message handler.
> 
> I think it would be better to remove the context creation from `createConnectionHandler` and pass the `subscriptionContextFn` to `SubscriptionConnection` constructor.
> But this rises an other issue concerning `connection_init` and message order.
> 
> Based on apollo implementation https://github.com/apollographql/subscriptions-transport-ws/blob/52758bfba6190169a28078ecbafd2e457a2ff7a8/src/server.ts and https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md, if an `onConnect` handler is defined and returns `false` a `GQL_START` message should return a `GQL_CONNECTION_ERROR`.

related to #207 I think





> @PabloSzx I just assigned myself as an ToDo item, because the person that has created the issue seems to be not interested in fixing & I have a slight feeling that this can hit us as well once we're done migrating from Apollo to Fastify. That being said, I would suggest that you can re-assign this to you & I also think it would be reasonable to fix it within this PR (of course, this is just my subjective opinion)

I will do, no problem, plus the #207

File: lib/subscription.js (hunk 1 above)
Comment (PabloSzx) [reply lib/subscription.js:31]: awaiting the context here doesn't let the socket connection be properly created, the possible promise should be started, but it's result is not used until the socket messages 'connection_init' / 'start'.

Comment (mcollina) [reply lib/subscription.js:31]: Then let's move where we do this operation. If the context should be created and awaited during `connection_init`, then let's do it there. This adds complexity that could bite us in the future.

File: lib/subscription-connection.js [hunk 3]
```diff
@@ -35,6 +35,7 @@ module.exports = class SubscriptionConnection {
     this.onConnect = onConnect
     this.subscriptionContexts = new Map()
     this.context = context
+    this.isReady = false
```
Comment (mcollina) [inline lib/subscription-connection.js:38]: where is `isReady = true` set?

Comment (PabloSzx) [reply lib/subscription-connection.js:38]: at the end of handleConnectionInit, it's to verify the message order as @PacoDu mentioned

File: lib/subscription.js (hunk 1 above)
Comment (PabloSzx) [reply lib/subscription.js:31]: The thing is, as I mentioned, should the context be created at socket creation or in `connection_init`?, as the test `subscription connection is closed if context function **throws**` suggests, it's still possible to make the context without the `connection_init` being received.

As I said previously:

> EDIT: The Context should be made (and it's possible errors, handled) in the request context, and the subcription connection should just receive the promise, since like the test 'subscription connection is closed if context function throws' in `subscription.js` test file suggests, it's possible to start the socket connection first without the 'connection_init' and the context should already be in process. Just passing the function to be executed in `subcription-connection.js` delays the promise unnecessarily.

File: lib/subscription-connection.js [hunk 4]
```diff
@@ -83,6 +90,17 @@ module.exports = class SubscriptionConnection {
   }
 
   async handleConnectionInit (data) {
+    if (this.context instanceof Promise) {
```
Comment (mcollina) [inline lib/subscription-connection.js:93]: remove this, there is no need for this check.

File: lib/subscription.js (hunk 1 above)
Comment (mcollina) [reply lib/subscription.js:31]: I would move it to https://github.com/mcollina/fastify-gql/pull/234/files#diff-d0a65557fba21a77676fdc6c8ab721c7R95

Comment (PabloSzx) [reply lib/subscription.js:31]: Then I will have to modify the mentioned test and give a function to the subscription connection that resolves the context instead of just receiving it.

File: test/subscription.js [hunk 5]
```diff
@@ -508,3 +513,316 @@ test('subscription connection is closed if context function throws', t => {
...
+    }
+  `
+
+  const resolvers = {
+    Query: {
+      add: (parent, { x, y }) => x + y
+    }
+  }
+
+  const wait = (amount = 0) => new Promise(resolve => setTimeout(resolve, amount))
```
Comment (mcollina) [inline test/subscription.js:714]: please use util.promisify instead.

File: test/subscription.js [hunk 6]
```diff
@@ -508,3 +513,316 @@ test('subscription connection is closed if context function throws', t => {
...
+
+  app.register(GQL, {
+    schema,
+    resolvers,
+    subscription: {
+      context: async function () {
+        await wait(200)
```
Comment (mcollina) [inline test/subscription.js:721]: Why is this timeout needed?

**Comment by wesselvdv** [comment]
I am hit big time by this atm, good to see that it's almost merged!

File: test/subscription.js (hunk 6 above)
Comment (PabloSzx) [reply test/subscription.js:721]: this timeout triggers the race condition of the socket not being created because of the context creation await, this simulates the reason this PR was created

Comment (mcollina) [reply test/subscription.js:722]: Then you can use the following instead:

```js
const immediate = promisify(setImmediate)

// in the test
await immediate()
```

Comment (PabloSzx) [reply test/subscription.js:722]: with setTimeout(() => {}, 0), which is what setImmediate does, the race condition was not happening, the number should be high for it to happen.

Comment (PabloSzx) [reply test/subscription.js:722]: the problem was not happening just because it was async, was because of the delay intrinsic the async, which is we are simulating with the delay 200, you can test this problem yourself removing the code that solves this and keeping the tests.

Comment (mcollina) [reply test/subscription.js:722]: Can we use the fake timers instead then? setTimeout introduce flakyness.

Comment (PabloSzx) [reply test/subscription.js:722]: are they being installed/used already somewhere in the code?

Comment (mcollina) [reply test/subscription.js:722]: https://github.com/mcollina/fastify-gql/blob/1335259f51710521b3d81cfb01e78d84d241577c/test/gateway/pollingInterval.js#L5 use the fake timers.

Comment (PabloSzx) [reply test/subscription.js:722]: I was checking the timers and they don't do what the test needs need to do, we need to actually make the socket wait, and the number needs to be 50ms+, the flakyness doesn't matter
